./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
./scheduler prio 100 homogeneous.txt
